### ISSUE TITLE
Replace crate failure

### ISSUE THREAD

**Issue by mucinoab** [arturomf94/bitsors#18]
`Failure` is officially deprecated/unmaintained as reported by the [Rust security advisory database](https://rustsec.org/advisories/RUSTSEC-2020-0036). 

What crate should we use to replace `failure`?

**Comment by nph4rd** [comment]
We could opt for either [anyhow](https://crates.io/crates/anyhow) or [eyre](https://crates.io/crates/eyre). I would be more inclined to have `anyhow`, since it looks like it is directly recommended in the [failure](https://github.com/rust-lang-nursery/failure) deprecation message so perhaps the substitution would be more seamless. What do you think? Also: would you be willing to work on this?
